// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartWMS.API.Infrastructure.Data;

#nullable disable

namespace SmartWMS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214140000_AddProductCategoryDefaults")]
    partial class AddProductCategoryDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This is a partial migration - just adds columns to ProductCategories
            // Full model snapshot is in ApplicationDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
